# Generated by Django 3.0.6 on 2020-05-06 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soonuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soonuser',
            name='username',
            field=models.CharField(max_length=32, verbose_name='사용자명'),
        ),
    ]
