# Generated by Django 3.0.6 on 2020-05-07 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soonuser', '0002_auto_20200506_1209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soonuser',
            options={'verbose_name': '패캠 사용자', 'verbose_name_plural': '패캠 사용자'},
        ),
        migrations.AddField(
            model_name='soonuser',
            name='useremail',
            field=models.EmailField(default='test@gmail.com', max_length=128, verbose_name='사용자 이메일'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='soonuser',
            name='username',
            field=models.CharField(max_length=64, verbose_name='사용자명'),
        ),
    ]
